<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>audio_processor</name>
  <version>0.0.0</version>
  <description>Audio processing node for STT using OpenVINO</description>
  <maintainer email="yuki.nakagawa@intel.com">root</maintainer>
  <license>Apache-2.0</license>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <exec_depend>ffmpeg-python</exec_depend>
  <exec_depend>pydub</exec_depend>
  <exec_depend>numpy</exec_depend>
  <exec_depend>openvino</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>

