pipeline {
    agent any
    environment {
        // Test_Server is the local test machine.
        Test_Server = "robotics-testNUC11"
        WORKSPACE_PATH = "/home/intel/ros2_openvino_toolkit"
    }
    stages {
        stage('Test Ros2 Galatic') {
            steps {
                script {
                    def flag = sh script: "ssh intel@$Test_Server 'cd $WORKSPACE_PATH && docker images | grep ros2_openvino_test'", returnStatus: true
                    if (flag == 0) {
                        docker rmi -f ros2_openvino_test
                    }
                    def test_result = sh script: "ssh intel@$Test_Server 'cd $WORKSPACE_PATH && ./self_host_test_ros2_openvino.sh '", returnStatus: true
                    if (test_result == 0) {
                        echo "test pass"
                    } else {
                        echo "test fail"
                        exit -1
                    }
                
                }
            }
        }

    }

}
