// Copyright (c) 2018-2022 Intel Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/**
* @brief A header file with declaration for RvizOutput Class
* @file rviz_output.h
*/

#ifndef OPENVINO_WRAPPER_LIB__OUTPUTS__RVIZ_OUTPUT_HPP_
#define OPENVINO_WRAPPER_LIB__OUTPUTS__RVIZ_OUTPUT_HPP_

#include <rclcpp/rclcpp.hpp>
#include <std_msgs/msg/header.hpp>
#include <vector>
#include <string>
#include <memory>

#include "openvino_wrapper_lib/outputs/base_output.hpp"
#include "openvino_wrapper_lib/outputs/image_window_output.hpp"

namespace Outputs
{
/**
 * @class RvizOutput
 * @brief This class handles and shows the detection result with rviz.
 */
class RvizOutput : public BaseOutput
{
public:
  explicit RvizOutput(std::string output_name, const rclcpp::Node::SharedPtr node=nullptr);
  /**
   * @brief Construct frame for rviz
   * @param[in] A frame.
   */
  void feedFrame(const cv::Mat &) override;
  /**
   * @brief Show all the contents generated by the accept
   * functions with rviz.
   */
  void handleOutput() override;
  /**
   * @brief Generate rviz output content according to
   * the face reidentification result.
   * @param[in] A face reidentification result objetc.
   */
  void accept(const std::vector<openvino_wrapper_lib::FaceReidentificationResult> &) override;
  /**
   * @brief Generate rviz output content according to
   * the landmarks detection result.
   * @param[in] A landmarks detection result objetc.
   */
  void accept(const std::vector<openvino_wrapper_lib::LandmarksDetectionResult> &) override;
  /**
   * @brief Generate rviz output content according to
   * the person attributes detection result.
   * @param[in] A person attributes detection result objetc.
   */
  void accept(const std::vector<openvino_wrapper_lib::PersonAttribsDetectionResult> &) override;
  /**
   * @brief Generate rviz output content according to
   * the person reidentification result.
   * @param[in] A person reidentification result objetc.
   */
  void accept(const std::vector<openvino_wrapper_lib::PersonReidentificationResult> &) override;
  /**
   * @brief Generate rviz output content according to
   * the face detection result.
   * @param[in] A face detection result objetc.
   */
  void accept(const std::vector<openvino_wrapper_lib::FaceDetectionResult> &) override;
  /**
   * @brief Generate rviz output content according to
   * the object detection result.
   * @param[in] results A bundle of object detection results.
   */
  void accept(const std::vector<openvino_wrapper_lib::ObjectDetectionResult> &) override;
  /**
 * @brief Generate rviz output content according to
 * the object segmentation result.
 * @param[in] results A bundle of object segmentation results.
 */
  void accept(const std::vector<openvino_wrapper_lib::ObjectSegmentationResult> &) override;
  /**
 * @brief Generate rviz output content according to
 * the object segmentation result.
 * @param[in] results A bundle of object segmentation maskrcnn results.
 */
  void accept(const std::vector<openvino_wrapper_lib::ObjectSegmentationMaskrcnnResult> &) override;
  /**
   * @brief Generate rviz output content according to
   * the emotion detection result.
   * @param[in] A emotion detection result objetc.
   */
  void accept(const std::vector<openvino_wrapper_lib::EmotionsResult> &) override;
  /**
   * @brief Generate rviz output content according to
   * the age and gender detection result.
   * @param[in] A head pose detection result objetc.
   */
  void accept(const std::vector<openvino_wrapper_lib::HeadPoseResult> &) override;
  /**
   * @brief Generate rviz output content according to
   * the headpose detection result.
   * @param[in] An age gender detection result objetc.
   */
  void accept(const std::vector<openvino_wrapper_lib::AgeGenderResult> &) override;
  /**
   * @brief Generate rviz output content according to
   * the human pose estimation result.
   * @param[in] An human pose estimation result.
   */
  void accept(const std::vector<openvino_wrapper_lib::HumanPoseEstimationResult> &) override;

private:
  std::shared_ptr<rclcpp::Node> node_;
  rclcpp::Publisher<sensor_msgs::msg::Image>::SharedPtr pub_image_;
  std::shared_ptr<sensor_msgs::msg::Image> image_topic_;
  std::shared_ptr<Outputs::ImageWindowOutput> image_window_output_;
};
}  // namespace Outputs
#endif  // OPENVINO_WRAPPER_LIB__OUTPUTS__RVIZ_OUTPUT_HPP_
