# GitHub Actions workflow file to run basic functional tests for ros2_openvino_toolkit on multiple Ubuntu versions

name: Basic_Func_CI 

on:
  push:
    branches: [ "master", "ros2" ]
  pull_request:
    branches: [ "master", "ros2" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ${{ matrix.ubuntu-version }}
    strategy:
      fail-fast: false
      matrix:
        ubuntu-version: [ubuntu-22.04, ubuntu-24.04]
        include:
          - ubuntu-version: ubuntu-22.04
            dockerfile: docker/ros2_ov202x/ros2_humble/Dockerfile
          - ubuntu-version: ubuntu-24.04
            dockerfile: docker/ros2_ov2025/ros2_jazzy/Dockerfile

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: ros2_openvino_toolkit_test
        run: |
            df -h
            sudo docker rmi $(docker image ls -aq) || true
            sudo swapoff /swapfile || true
            sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc  || true
            mkdir -p ../workspace
            cp -r ${GITHUB_WORKSPACE}/.ci_local_test/ros2_openvino_toolkit_test ../workspace
            cp -r ${GITHUB_WORKSPACE}  ../workspace/ros2_openvino_toolkit_test
            ls ${GITHUB_WORKSPACE}/${{ matrix.dockerfile }}
            cp ${GITHUB_WORKSPACE}/${{ matrix.dockerfile }} ../workspace/ros2_openvino_toolkit_test/Dockerfile
            ls ../workspace/ros2_openvino_toolkit_test/Dockerfile
            cd ../workspace/ros2_openvino_toolkit_test && ./docker_run.sh

