name: Ubuntu-22.04-Humble-CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the ros2 branch
on:
  push:
    branches: [ "ros2" ]
  pull_request:
    branches: [ "ros2" ]

permissions: read-all

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    # install ros2 humble
    - uses: ros-tooling/setup-ros@v0.7
      with:
        required-ros-distributions: humble
    - run: "source /opt/ros/humble/setup.bash && ros2 run --help"

    # install openvino 2022.3 (latest compatible with ros2 branch)
    - name: install openvino 2022.3
      run: |
        # https://docs.openvino.ai/2022.3/openvino_docs_install_guides_installing_openvino_apt.html
        sudo apt update && sudo apt install -y curl gnupg2 lsb-release
        wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
        sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
        echo "deb https://apt.repos.intel.com/openvino/2022 jammy main" | sudo tee /etc/apt/sources.list.d/intel-openvino-2022.list
        sudo apt update
        sudo apt-cache search openvino
        sudo apt-get install -y openvino-2022.3.0
        ls -lh /opt/intel/openvino_2022
        source /opt/intel/openvino_2022/setupvars.sh

    # install librealsense2
    - name: install librealsense2
      run: |
        # https://github.com/IntelRealSense/librealsense/blob/master/doc/distribution_linux.md
        sudo mkdir -p /etc/apt/keyrings
        curl -sSf https://librealsense.intel.com/Debian/librealsense.pgp | sudo tee /etc/apt/keyrings/librealsense.pgp > /dev/null
        echo "deb [signed-by=/etc/apt/keyrings/librealsense.pgp] https://librealsense.intel.com/Debian/apt-repo jammy main" | sudo tee /etc/apt/sources.list.d/librealsense.list
        sudo apt-get update && sudo apt-get install -y librealsense2-dev librealsense2
        dpkg -l |grep realsense

    # build ros2 openvino toolkit
    - name: build ros2 openvino toolkit
      run: |
        mkdir -p ~/ros2_ws/src
        env
        cp -rf ${GITHUB_WORKSPACE} ~/ros2_ws/src
        cd ~/ros2_ws/src
        git clone https://github.com/intel/ros2_object_msgs.git
        cd ros2_object_msgs && git checkout ros2 && cd ~/ros2_ws/
        source /opt/ros/humble/setup.bash
        source /opt/intel/openvino_2022/setupvars.sh
        colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release
